version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    main: ./.

    binary: nbx

    ldflags:
      - -s -w -X '{{.ModulePath}}/cmd.version={{.Version}}'
      - -X '{{.ModulePath}}/cmd.commit={{.Commit}}'
      - -X '{{.ModulePath}}/cmd.date={{.Date}}'

archives:
  - formats:
      - tar.gz
      - zip

    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    files:
      - none*
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    name: nbx

  prerelease: auto
  draft: false
