package enumtpl

const EnumTplInt = `// Code generated by github.com/byte4cat/enumgo; DO NOT EDIT.

package {{.Package}}

import (
	"fmt"
)

{{- if .Def.Description }}
	{{ formatMultilineComment .Def.Description }}
{{- end }}
type {{.Def.Type}} int

const (
{{- range .Def.Values }}
{{- if .Comment }}
	{{ formatMultilineComment .Comment }}
{{- end }}
	{{$.Def.Type}}_{{.Name}} {{$.Def.Type}} = {{.Value}}
{{- end }}
)

var {{.Def.Type | lower}}ToString = map[{{.Def.Type}}]string{
{{- range .Def.Values }}
	{{$.Def.Type}}_{{.Name}}: "{{.Name }}",
{{- end }}
}

var stringTo{{.Def.Type}} = map[string]{{.Def.Type}}{
{{- range .Def.Values }}
	"{{.Name }}": {{$.Def.Type}}_{{.Name}},
{{- end }}
}

func (e {{.Def.Type}}) String() string {
	return {{.Def.Type | lower}}ToString[e]
}

func (e {{.Def.Type}}) IsValid() bool {
	_, ok := {{.Def.Type | lower}}ToString[e]
	return ok
}

func Parse{{.Def.Type}}String(s string) ({{.Def.Type}}, error) {
	if val, ok := stringTo{{.Def.Type}}[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("invalid {{.Def.Type}}: %s", s)
}

func {{.Def.Type}}Options() []{{.Def.Type}} {
	return []{{.Def.Type}}{
{{- range .Def.Values }}
		{{$.Def.Type}}_{{.Name}},
{{- end }}
	}
}
`
